# Generated by Django 3.2 on 2023-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=None),
        ),
    ]
