# Generated by Django 3.2 on 2023-01-23 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220517_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_question', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('05e370c3-6c7d-46fe-a45c-1c57f35ffbd8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('05e370c3-6c7d-46fe-a45c-1c57f35ffbd8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
